config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :items
  resources :categories, only: [:index, :show]

   root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  def index
    @categories = Category.all
  end

  def show

  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:search]
      @items = Item.search(params[:search]).order('name ASC')
    else
      @items = Item.all.order('name ASC')
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/index.html.haml
-#%p.categories Product Categories
.table-body
  .breadcrumb
    %ul
      %li Product Category
%table
  %tbody
    - @categories.each do |category|
      %td.grid= link_to category.name, category, class: "category-text"

app/views/categories/show.haml
.table-body
  .breadcrumb
    %ul
      %li= link_to "Product Categories | ", root_path
      %li= @category.name
  %table
    %thead
      %tr
        %th.th-name Name
        %th.th-srp SRP
        %th.th-price Price
        -#%th Description
        %th{:colspan => "3"}
    %tbody
      - @category.items.each do |item|
        %tr
          %td= link_to item.name, item
          %td= item.srp
          %td= item.price

app/views/items/_form.html.haml
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :price
    %br/
    = f.text_field :price
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/items/edit.html.haml
%h1 Editing Item
= render 'form'
= link_to 'Show', @item
|
= link_to 'Back', items_path

app/views/items/index.html.haml
-#.header
  -#%h1 Price Watch
-#%hr
-#-#%p#notice= notice
-#.search
  -#= form_tag(items_path, method: 'get', id: "search-form") do
    -#= text_field_tag :search, params[:search], placeholder: "Search Items", class: "search-field"
    -#= submit_tag "Search", class: "search-button"
-#%hr
%table
  %thead
    %tr
      %th.th-name Name
      %th.th-srp SRP
      -#%th Description
      %th{:colspan => "2"}
  %tbody
    - @items.each do |item|
      %tr
        %td= link_to item.name, item
        %td= item.price
        -#%td= item.description
        -#%td= link_to 'Show', item
        -#%td= link_to 'Edit', edit_item_path(item)
        -#%td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
-#= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New Item
= render 'form'
= link_to 'Back', items_path

app/views/items/show.html.haml
.table-body
  .breadcrumb
    %ul
      %li= link_to "Product Categories | ", root_path
      %li= link_to "#{@item.category.name} | ", category_path(@item.category), method: :get
      %li= @item.name
  %p
    %strong Name:
    = @item.name
  %p
    %strong SRP:
    = @item.srp
  %p
    %strong Price:
    = @item.price
  %p
    %strong Description:
    = @item.description
  -#= link_to 'Edit', edit_item_path(@item)
  -#|
  -#%p= link_to 'Back', items_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pricewatch
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .header
      .header-logo
        = link_to image_tag( 'logo.png'), root_path
      .header-text
        %h1= link_to "BANTAY PRESYO", root_path
        %h2
          with updates from the
          %br
          Department of Trade & Industry
    .search-panel
      .search
        = form_tag(items_path, method: 'get', id: "search-form") do
          = text_field_tag :search, params[:search], placeholder: "Search Items", class: "search-field"
          = submit_tag "Search", class: "search-button"
    = yield